language: python

matrix:

  include:
    - python: 3.6
      env: DJANGO_VERSION="Django>=2.2,<2.3"
    - python: 3.7
      env: DJANGO_VERSION="Django>=2.2,<2.3"
    - python: 3.8
      env: DJANGO_VERSION="Django>=2.2.8,<2.3"
    - python: 3.9
      env: DJANGO_VERSION="Django>=2.2.8,<2.3"

    - python: 3.6
      env: DJANGO_VERSION="Django>=3.0,<3.1"
    - python: 3.7
      env: DJANGO_VERSION="Django>=3.0,<3.1"
    - python: 3.8
      env: DJANGO_VERSION="Django>=3.0,<3.1"
    - python: 3.9
      env: DJANGO_VERSION="Django>=3.0,<3.1"

    - python: 3.6
      env: DJANGO_VERSION="Django>=3.1,<3.2"
    - python: 3.7
      env: DJANGO_VERSION="Django>=3.1,<3.2"
    - python: 3.8
      env: DJANGO_VERSION="Django>=3.1,<3.2"
    - python: 3.9
      env: DJANGO_VERSION="Django>=3.1,<3.2"

before_install:
  - export DJANGO_SETTINGS_MODULE=sites.test.settings

install:
  - pip install "$DJANGO_VERSION"
  - pip install -r requirements.test.txt
  - pip install codecov

script: coverage run manage.py test tests

notifications:
  email: false

after_success:
  - codecov

